### PR TITLE
Add wall breaker

### LINKED ISSUE #11: Add wall-breaker with random spawn
Add wall breaker that spawns randomly in different spawn points across the maze.
Will be able to break one wall piece, allowing the user to break into the exit.

Maybe add a feature in which if the player accidentally uses their wall breaker not on the exit, another one will spawn? So that the player can't get stuck.

### PR DESCRIPTION
**Pull request by rowan04**
- adds wall breaker
- it spawns in one of 12 set locations, at random
- this does not add functionality
- can be picked up by player
- when picked up, object is destroyed
- when player has wall breaker, breakable walls can be destroyed

resolves #11

### CODE REVIEW

**Comment by rowan04** [comment]
this does not add the feature of the wall breaker only showing up when near it - that'll need adding later

**Review by Will-Cross1 — APPROVED** [review]
looks good

**Comment by Will-Cross1** [comment]
adding functionality would be very easy

on the bit in player saying you can't pass through damaged walls

make it so you just delete the wall instead

**Comment by rowan04** [comment]
> adding functionality would be very easy
> 
> on the bit in player saying you can't pass through damaged walls
> 
> make it so you just delete the wall instead

huh? wdym

**Comment by Will-Cross1** [comment]
```
if (isTouching(Breakable.class))
        {
            setLocation(getX()-dx, getY()-dy);
        }
```

instead of set location, it. checks if you have a wall breaker and if you do it deletes that actor

**Comment by Will-Cross1** [comment]
then can you delete the actor from the if statement?

**Comment by rowan04** [comment]
> ```
> if (isTouching(Breakable.class))
>         {
>             setLocation(getX()-dx, getY()-dy);
>         }
> ```
> 
> instead of set location, it. checks if you have a wall breaker and if you do it deletes that actor

wait actually where are you finding that line. is it not one i removed?

**Comment by Will-Cross1** [comment]
might be I was looking it the non committed player file

**Comment by rowan04** [comment]
> might be I was looking it the non committed player file

probably. the code works, theres no problems there

**Pull request merged**
